### ISSUE TITLE
Thank you for your interests!

### ISSUE THREAD

**Issue by HarryXD2018** [HarryXD2018/EngagementPrediction#1]
We haven't finished the coding yet, yet please keep watching us!
Thank you.

**Comment by AndrewYB** [comment]
hi,could you open complete code ?

**Comment by HarryXD2018** [comment]
Hello, I am glad that u r interested. In fact, I am sorry to let u know that this repo hasn't been updated because I am no longer in charge of this task. I would probably delete this repo. 

There are numerous engagement prediction tasks on GitHub, u can take a look. 

Good luck!
